tags:
  - $COMMIT_SHA
  - $SHORT_SHA
  - arch-repo
  - arch-repo-aur
substitutions:
  _IMG: arch-repo-builder
  _BKT: seankhliao-arch-repo
images:
  - gcr.io/$PROJECT_ID/$_IMG:latest
artifacts:
  objects:
    location: gs://$_BKT
    paths:
      - $_BKT/*

timeout: 1200s
steps:
  - id: precache
    waitFor: ["-"]
    name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - gs://$_BKT
      - .
  - id: builder
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker:latest
    args:
      - build
      - -t=gcr.io/$PROJECT_ID/$_IMG:latest
      - .

  - id: build dive
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=dive
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build downgrade
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=downgrade
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build google-chrome-dev
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=google-chrome-dev
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build google-chrome
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=google-chrome
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build kitty-git
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=kitty-git
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build neovim-git
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=neovim-git
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build neovim-plug-git
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=neovim-plug-git
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build spotify
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=spotify
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build sway-service
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=sway-service
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build wl-clipboard-x11
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=wl-clipboard-x11
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build yay-bin
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=yay-bin
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh
  - id: build zsh-completions-git
    waitFor: ["precache", "builder"]
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    env:
        - PKG=zsh-completions-git
        - OUTDIR=$_BKT
    args:
        - ./archinstall.sh

  - id: collect
    name: gcr.io/$PROJECT_ID/$_IMG:latest
    entrypoint: /usr/bin/bash
    args:
      - -c
      - sudo repo-add -R $_BKT/seankhliao.db.tar.zst $_BKT/*.pkg.tar.zst
