name: docker
on:
  push:
    paths:
      - ".github/workflows/docker.yaml"
      - "Dockerfile"
  schedule:
    - cron: "0 0 * * *"
env:
  REGISTRY: docker.pkg.github.com
  IMG: yay
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: login
        run: docker login ${REGISTRY} -u ${GITHUB_REPOSITORY%/*} -p ${TOKEN}
        env:
          TOKEN: ${{ secrets.PAT }}
      - name: build
        run: docker build -t ${REGISTRY}/${GITHUB_REPOSITORY}/${IMG}:latest .
      - name: push latest
        run: docker push ${REGISTRY}/${GITHUB_REPOSITORY}/${IMG}:latest
