name: workflow
on:
  push:
    paths-ignore:
      - "Dockerfile"
      - ".github/workflows/docker.yaml"
    branch:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG: seankhliao/arch-repo/yay:latest
      REGISTRY: docker.pkg.github.com
      PACKAGES: yay-bin google-chrome-dev google-chrome neovim-plug-git tag-ag wl-clipboard-x11
      repo: seankhliao
    steps:
      - uses: actions/checkout@master

      - name: login
        run: docker login ${REGISTRY} -u ${GITHUB_REPOSITORY%/*} -p ${TOKEN}
        env:
          TOKEN: ${{ secrets.PAT }}

      - run: mkdir build && chmod 0777 build
      - run: docker run -u user -v $(pwd)/build:/home/user/build -v $(pwd):/mnt $REGISTRY/$IMG yay -S --noconfirm --builddir /home/user/build $PACKAGES

      - run: mkdir pkgs || true && chmod 0777 pkgs && for p in build/*; do cp -v $p/*.pkg.tar.zst pkgs; done
      - run: docker run -v $(pwd):/workspace -w /workspace $REGISTRY/$IMG repo-add -R pkgs/$repo.db.tar.zst pkgs/*.pkg.tar.zst
      - run: rm pkgs/$repo.db pkgs/$repo.files
      - run: cp pkgs/$repo.db.tar.zst pkgs/$repo.db && cp pkgs/$repo.files.tar.zst pkgs/$repo.files

      - run: git config user.email "workflow@github.actions" && git config user.name "Github Actions" && git checkout master
      - run: git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/seankhliao/arch-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add pkgs && git commit -m "update pkgs" && git push
