name: workflow
on:
  push:
    branch:
      - master
  schedule:
    - cron: "0 0 */6 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    env:
      PACKAGES: yay-bin google-chrome-dev google-chrome
      repo: seankhliao
    steps:
      - uses: actions/checkout@master

      - run: useradd -G wheel yay && echo "%wheel ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      - run: pacman -Syu --noconfirm git base-devel

      - run: git clone https://aur.archlinux.org/yay-bin.git
      - run: chown yay:yay -R .
      - run: cd yay-bin && su -c "makepkg -i --noconfirm" - yay && mkdir /home/yay && chown yay:yay /home/yay

      - run: mkdir build && chown yay:yay build && su -c "yay -S --noconfirm --builddir build $PACKAGES" - yay
      - run: bash -c "mkdir pkgs && for pkg in build/*; do repo-add -R pkgs/$repo.db.tar.zst $pkg/*.pkg.zst; done"
      - run: git status -s
      - run: git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/seankhliao/arch-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add pkgs && git commit -m "update pkgs" && git push
