name: workflow
on:
  push:
    paths-ignore:
      - "Dockerfile"
      - ".github/workflows/docker.yaml"
    branch:
      - master
  schedule:
    - cron: "0 0 */6 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGES: yay-bin google-chrome-dev google-chrome
      repo: seankhliao
    steps:
      - uses: actions/checkout@master

      - name: login
        run: docker login ${REGISTRY} -u ${GITHUB_REPOSITORY%/*} -p ${TOKEN}
        env:
          TOKEN: ${{ secrets.PAT }}

      - run: mkdir build && chown 1000:1000 build
      - run: docker run -u user -v $(pwd)/build:/home/user/build docker.pkg.github.com/seankhliao/arch-repo/yay:latest yay -S --noconfirm --builddir /home/user/build $PACKAGES

      - run: for p in build/*; do cp $p/*.pkg.zst pkgs; done
      - run: repo-add -R pkgs/$repo.db.tar.zst pkgs/*.pkg.zst

      - run: git status -s
      - run: git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/seankhliao/arch-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add pkgs && git commit -m "update pkgs" && git push
